# Generated by Django 4.2.16 on 2024-10-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0022_storagelocation_max_limit_alter_chemical_uom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='uom',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending higher approval', 'Pending higher approval'), ('Ordered', 'Ordered'), ('Order in progress', 'Order in progress'), ('Stored', 'Stored'), ('Approved by higher', 'Approved by higher'), ('Rejected by supervisor', 'Rejected by supervisor'), ('Closed', 'Closed'), ('Rejected by higher', 'Rejected by higher'), ('Delivered', 'Delivered'), ('Approved by supervisor', 'Approved by supervisor'), ('Rejected', 'Rejected'), ('Pending approval', 'Pending approval'), ('Requested', 'Requested'), ('Received', 'Received')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='disposal_status',
            field=models.CharField(choices=[('NOT YET', 'Not yet'), ('DISPOSED', 'Disposed')], default='Not yet', max_length=20),
        ),
    ]
