# Generated by Django 4.2.16 on 2024-10-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0023_alter_chemical_uom_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='uom',
            field=models.CharField(choices=[('ml', 'ml'), ('g', 'g')], default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Received', 'Received'), ('Pending approval', 'Pending approval'), ('Closed', 'Closed'), ('Rejected', 'Rejected'), ('Order in progress', 'Order in progress'), ('Delivered', 'Delivered'), ('Rejected by supervisor', 'Rejected by supervisor'), ('Requested', 'Requested'), ('Stored', 'Stored'), ('Approved by supervisor', 'Approved by supervisor'), ('Rejected by higher', 'Rejected by higher'), ('Pending higher approval', 'Pending higher approval'), ('Ordered', 'Ordered'), ('Approved by higher', 'Approved by higher')], default='Requested', max_length=30),
        ),
    ]
