# Generated by Django 4.2.16 on 2024-10-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0024_alter_chemical_uom_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='uom',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Approved by higher', 'Approved by higher'), ('Order in progress', 'Order in progress'), ('Ordered', 'Ordered'), ('Received', 'Received'), ('Rejected', 'Rejected'), ('Closed', 'Closed'), ('Rejected by supervisor', 'Rejected by supervisor'), ('Pending higher approval', 'Pending higher approval'), ('Pending approval', 'Pending approval'), ('Requested', 'Requested'), ('Delivered', 'Delivered'), ('Rejected by higher', 'Rejected by higher'), ('Approved by supervisor', 'Approved by supervisor'), ('Stored', 'Stored')], default='Requested', max_length=30),
        ),
    ]
