# Generated by Django 4.2.16 on 2024-10-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0026_auto_20241019_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending approval', 'Pending approval'), ('Closed', 'Closed'), ('Stored', 'Stored'), ('Delivered', 'Delivered'), ('Pending higher approval', 'Pending higher approval'), ('Rejected by supervisor', 'Rejected by supervisor'), ('Approved by supervisor', 'Approved by supervisor'), ('Order in progress', 'Order in progress'), ('Rejected', 'Rejected'), ('Received', 'Received'), ('Ordered', 'Ordered'), ('Requested', 'Requested'), ('Approved by higher', 'Approved by higher'), ('Rejected by higher', 'Rejected by higher')], default='Requested', max_length=30),
        ),
    ]
