# Generated by Django 4.2.16 on 2024-10-21 03:28

from django.db import migrations, models
import furc.models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0027_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exp_procedure',
            field=models.FileField(blank=True, null=True, upload_to=furc.models.custom_file_upload_path_exp),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending higher approval', 'Pending higher approval'), ('Stored', 'Stored'), ('Pending approval', 'Pending approval'), ('Rejected', 'Rejected'), ('Rejected by supervisor', 'Rejected by supervisor'), ('Received', 'Received'), ('Requested', 'Requested'), ('Approved by higher', 'Approved by higher'), ('Delivered', 'Delivered'), ('Ordered', 'Ordered'), ('Approved by supervisor', 'Approved by supervisor'), ('Closed', 'Closed'), ('Rejected by higher', 'Rejected by higher'), ('Order in progress', 'Order in progress')], default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='risk_assessment',
            field=models.FileField(blank=True, null=True, upload_to=furc.models.custom_file_upload_path_risk),
        ),
    ]
