# Generated by Django 4.2.16 on 2024-10-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furc', '0028_alter_order_exp_procedure_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Order in progress', 'Order in progress'), ('Stored', 'Stored'), ('Rejected by higher', 'Rejected by higher'), ('Approved by supervisor', 'Approved by supervisor'), ('Approved by higher', 'Approved by higher'), ('Pending approval', 'Pending approval'), ('Rejected', 'Rejected'), ('Pending higher approval', 'Pending higher approval'), ('Closed', 'Closed'), ('Ordered', 'Ordered'), ('Received', 'Received'), ('Rejected by supervisor', 'Rejected by supervisor'), ('Delivered', 'Delivered')], default='Requested', max_length=30),
        ),
    ]
